Changed GIF
mexili/incogly pull request #105
Opened 2021-07-01 11:09 UTC by ZohebMOPO

Any more issues just let me know
![img](https://user-images.githubusercontent.com/72716462/124114929-cfb4b280-da8a-11eb-9669-32f8950edd75.JPG)

2021-07-01 11:14 UTC, sansyrox requested changes

2021-07-01 11:14 UTC, sansyrox commented on src/components/Home/index.jsx
> +					style={{ border: "1px", borderRadius: 75 + "px" }}
@ZohebMOPO , please don't use inline styling here. Can you shift it to the relevant scss file?

2021-07-01 11:14 UTC, sansyrox commented on src/components/Home/index.jsx
> +					style={{ border: "1px", borderRadius: 75 + "px" }}
Also, the gif looks very nice 💯

2021-07-01 11:21 UTC, ZohebMOPO commented
Yeah sure. I will try to take those in scss.

2021-07-01 13:21 UTC, ZohebMOPO commented
@sansyrox I migrated the Inline CSS to SCSS. It works fine! I tested it
![meet2](https://user-images.githubusercontent.com/72716462/124131371-5c686c00-da9d-11eb-955d-673950c01e71.JPG)

2021-07-01 15:14 UTC, merged

2021-07-02 18:37 UTC, sansyrox commented
@ZohebMOPO , can you share the original dribbble link of the gif?

2021-07-03 03:06 UTC, ZohebMOPO commented
https://cdn.dribbble.com/users/37380/screenshots/10883216/zoom-party4_12fps.gif