FIXED - Solve GO To HOME issue and Implement Functional component
mexili/incogly pull request #43
Opened 2021-01-03 17:49 UTC by trishnakalita660

### What is the change?
Converted NotFound.js into Fuctional Component and "GO TO HOME" button into Link .

### What does it fix/add?
Fixed the issue with "GO TO HOME" in NotFound.js

### How was it tested?
Tested locally and it was working like it was supposed to.

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [ ] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):

2021-01-03 18:49 UTC, sansyrox requested changes
Please remove `package-lock.json`, all good otherwise.

2021-01-04 04:55 UTC, trishnakalita660 commented
Removed the package-lock.json file.

2021-01-04 06:15 UTC, sansyrox commented
Thank you @trishnakalita660 ! This looks good 🔥

2021-01-04 06:15 UTC, sansyrox approved these changes

2021-01-04 06:15 UTC, merged