Commiting to refactor-branch
mexili/incogly pull request #88
Opened 2021-06-07 08:57 UTC by ZohebMOPO

### What is the change?
Changed the branch.

### What does it fix/add?

### How was it tested?

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [ ] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

### Screenshots (if appropriate):

2021-06-07 14:29 UTC, sansyrox commented
Hi @ZohebMOPO , is this up for review?

2021-06-07 14:34 UTC, ZohebMOPO commented
Review?

2021-06-07 14:54 UTC, sansyrox commented
> Oh review, I haven't fixed the last thing, and Idk how will I fix it.
That's alright. Can you mention the problems solved in the description of the PR?

2021-06-07 15:25 UTC, ZohebMOPO commented
Yeah I just added

2021-06-07 18:05 UTC, sansyrox requested changes

2021-06-07 18:05 UTC, sansyrox commented on src/components/Video/index.jsx
> +							<div className="pair">
Hey @ZohebMOPO , this looks good. However, the classes do not follow the BEM naming scheme.
Can you please change "pair" to something relevant? 
Here you can read more about BEM: http://getbem.com/introduction/

2021-06-08 02:48 UTC, ZohebMOPO commented
Yeah sure. I gave that classname in a hurry.

2021-06-09 11:29 UTC, sansyrox requested changes

2021-06-09 11:29 UTC, sansyrox commented on src/components/Video/Video.scss
> +	&__size {
@ZohebMOPO , in BEM we don't name attributes with an underscore. Change it to something like `username-selector__input_container`

2021-06-09 11:53 UTC, ZohebMOPO commented
Oh Ok.

2021-06-09 16:42 UTC, ZohebMOPO commented
Sorry, @sansyrox . I really never used those BEM class naming ways. But it was cool knowing something like this.

2021-06-09 17:12 UTC, sansyrox commented
> I really never used those BEM class naming ways.
No worries, @ZohebMOPO . I am glad you learnt something new 😄

2021-06-09 17:22 UTC, sansyrox approved these changes
LGTM 🚀

2021-06-09 17:22 UTC, merged